# Generated by Django 5.2.1 on 2025-09-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='lab_reports/')),
                ('original_text', models.TextField(blank=True, null=True)),
                ('summary_en', models.TextField(blank=True, null=True)),
                ('summary_hi', models.TextField(blank=True, null=True)),
                ('summary_ml', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='records.migrantworker')),
            ],
        ),
    ]
