# Generated by Django 5.2.1 on 2025-09-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_doctorpanel_delete_doctor1'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrantworker',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='records.doctorpanel'),
        ),
    ]
